{{ if .Values.globalRegistryMode }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.proxy" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: proxy
{{ end }}