{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.ingress.core" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  tls:
  - hosts:
    - {{ $ingress.host }}
  {{- if .Values.globalRegistryMode }}
    secretName: "tls-rancher-ingress"
  {{- else if $tls.secretName }}
    secretName: {{ $tls.secretName }}
  {{- else }}
    secretName: "{{ template "harbor.ingress.core" . }}"
  {{- end }}
{{- if .Values.globalRegistryMode }}
  rules:
  - http:
      paths:
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /api/projects
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /registry/
        backend:
          serviceName: {{ template "harbor.proxy" . }}
          servicePort: 80
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- else if eq .Values.expose.ingress.controller "gce" }}
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /api/*
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /service/*
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /v2/*
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /chartrepo/*
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /c/*
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- else }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.portal" . }}
          servicePort: 80
      - path: /api/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /service/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /v2/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
      - path: /c/
        backend:
          serviceName: {{ template "harbor.core" . }}
          servicePort: 80
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
{{- end }}
{{- end }}
